---

version: '3.7'
services:
  itk:
    build:
      context: .
      dockerfile: girder_worker.docker
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
    image: "xkortex/girder_worker-${OS_BASE}-${OS_VERS}:latest"

...
