---

version: '3.7'
services:
  girder_worker:
    build:
      context: .
      dockerfile: girder_worker.docker
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
    image: "${IMAGE_REGISTRY}/girder_worker-${OS_BASE}-${OS_VERS}:latest"

...
