---

version: '3.7'
services:
  ## Essential packages for building
  buildees:
    build:
      context: .
      dockerfile: general/build-essential.docker
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
    image: "${IMAGE_REGISTRY}/${OS_BASE}:${OS_VERS}-buildees"
  pysci:
    build:
      context: .
      dockerfile: general/pysci.docker
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
    image: "${IMAGE_REGISTRY}/${OS_BASE}:${OS_VERS}-pysci"
  cvfull:
    build:
      context: .
      dockerfile: general/cvfull.docker
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
    image: "${IMAGE_REGISTRY}/${OS_BASE}:${OS_VERS}-cvfull"
  toolbox:
    build:
      context: .
      dockerfile: toolbox.df
    image: "${IMAGE_REGISTRY:-xkortex}/toolbox:latest"
...
