---

version: '3.7'
services:
  # our own container for opencv deps
  dummy:
    build:
      context: .
      dockerfile: dummy.docker
      args:
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}

    image: xkortex/dummy
...
