---

version: '3.7'
services:
  # our own container for opencv deps
  dummy:
    build:
      context: .
      dockerfile: dummy.docker
#      network: host
      args:
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
        http_proxy: "http://athena:3142/"


    image: xkortex/dummy
...
