---

version: '3.7'
services:
  ## Essential packages for building
  fork:
    build:
      context: .
      dockerfile: fork.df
      args:
        DO_APT: "${DO_APT}"
        DO_COPY: "${DO_COPY}"
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
    image: "${IMAGE_REGISTRY:-xkortex}/${OS_BASE:-ubuntu}:${TAG:-latest}-${DO_APT:-false}"

