---

version: '3.7'
services:
  viame_girder_worker:
    build:
      context: .
      dockerfile: viame_girder_worker.docker
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
        TAG: "${TAG:-latest}"
    image: "${IMAGE_REGISTRY}/viame_girder_worker-${OS_BASE}-${OS_VERS}:latest"

...
