---

version: '3.7'
services:
  # our own container for opencv deps
  opencv:
    build:
      context: .
      dockerfile: opencv.docker
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
        SUBTAG: cvfull
        OPENCV_VERSION: $OPENCV_VERSION
    image: "${IMAGE_REGISTRY}/py2-opencv:$OPENCV_VERSION"
...
