---

version: '3.7'
services:
  itk:
    build:
      context: .
      dockerfile: itk.docker
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
        VERS_ITK: ${VERS_ITK}
        SUBTAG: cvfull
    image: "${IMAGE_REGISTRY}/itk-${OS_VERS}:$VERS_ITK"
  itk-latest:
    build:
      context: .
      dockerfile: itk-latest.docker
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
        VERS_ITK: latest
        SUBTAG: cvfull
    tty: true
    command: sh
    volumes:
      - "workspace:/ws"
    image: "${IMAGE_REGISTRY}/itk-${OS_VERS}:latest"

volumes:
  workspace:
    labels:
      com.kitware.description: "Persistence for interactive development"

...
