---

version: '3.7'
services:
  ## Essential packages for building
  buildees:
    build:
      context: .
      dockerfile: cmake.docker
      args:
        OS_BASE: ${OS_BASE}
        OS_VERS: ${OS_VERS}
    image: "xkortex/cmake:${OS_BASE}-${OS_VERS}"

...
