version: '3.7'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6380:6379"
#    network_mode: host
    volumes:
        - data:/data
    entrypoint: redis-server --appendonly yes
    restart: unless-stopped

volumes:
    data:
